blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/matthewbcool/Github-Custom-Forms/discussions/new?category=q-a
    about: Ask questions and discuss with the community
